samples/OWIN/ResourceAuthorization/WebApp/Controllers/TrackController.cs
using Chinook.DomainModel;
using Chinook.Repository;
using System.Web.Mvc;
using Thinktecture.IdentityModel.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    [ResourceAuthorize(ChinookResources.AlbumActions.Edit, ChinookResources.Track)]
    public class TrackController : Controller
    {
        IMusicRepository _musicRepository;

        public TrackController()
        {
            _musicRepository = new Chinook.Repository.InMemory.MusicRepository();
        }

        public ActionResult List(int albumID)
        {
            var tracks = _musicRepository.GetTracks(albumID);
            return PartialView(tracks);
        }

        public ActionResult Edit(int id)
        {
            var track = _musicRepository.GetTrack(id);
            if (track == null) return HttpNotFound();
            var vm = new TrackEditViewModel(_musicRepository, track);
            return View("Edit", vm);
        }

        [HttpPost]
        public ActionResult Update(Track track)
        {
            if (ModelState.IsValid)
            {
                _musicRepository.SaveTrack(track);
                return RedirectToAction("Edit", "Album", new { id = track.AlbumID });
            }
            else
            {
                var vm = new TrackEditViewModel(_musicRepository, track);
                return View("Edit", vm);
            }
        }

	}
}

samples/OWIN/ResourceAuthorization/WebApp/Views/Track/Edit.cshtml
@model WebApp.Models.TrackEditViewModel

@{
    ViewData["Title"] = "Edit Track ID " + Model.Track.ID;
}

<div class="page-header">
    <h1>Track Edit <small>ID: @Model.Track.ID</small></h1>
</div>

@using (Html.BeginForm("Update", "Track"))
{
    @*@Html.ValidationSummary("Please correct the following problems:")*@

    <fieldset class="col-sm-6">
        @Html.HiddenFor(x => x.Track.ID)
        <div class="form-group">
            @Html.LabelFor(x => x.Track.Name)
            @Html.ValidationMessageFor(x => x.Track.Name, null, new { @class = "label label-danger pull-right" })
            @Html.TextBoxFor(x => x.Track.Name, new { @class="form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.Track.AlbumID)
            @Html.ValidationMessageFor(x => x.Track.AlbumID, null, new { @class = "label label-danger pull-right" })
            @Html.DropDownListFor(x => x.Track.AlbumID, Model.Albums, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.Track.GenreID)
            @Html.ValidationMessageFor(x => x.Track.GenreID, null, new { @class = "label label-danger pull-right" })
            @Html.DropDownListFor(x => x.Track.GenreID, Model.Genres, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.Track.Price)
            @Html.ValidationMessageFor(x => x.Track.Price, null, new { @class = "label label-danger pull-right" })
            @Html.TextBoxFor(x => x.Track.Price, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <button class="btn btn-primary">Save Changes</button>
            @Html.ActionLink("Back to album", "Edit", "Album", new { id = Model.Track.AlbumID }, new { @class = "btn btn-default" })
        </div>
    </fieldset>
}

samples/OWIN/ResourceAuthorization/WebApp/Views/Track/List.cshtml
@model IEnumerable<Chinook.DomainModel.Track>

<div class="panel panel-default">
    <div class="panel-heading">Tracks</div>
    <ol class="list-group">
        @{
            var list = Model.ToArray();
        }
        @for (var i = 0; i < list.Length; i++)
        {
            var track = list[i];
            <li class="list-group-item track-list-item">
                <span class="label label-default">@(i+1)</span>
                @Html.ActionLink(track.Name, "Edit", new { id = track.ID })
            </li>
        }
    </ol>

</div>