samples/OWIN/ResourceAuthorization/WebApp/Controllers/AlbumController.cs
using Chinook.Repository;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Thinktecture.IdentityModel.Mvc;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    [ResourceAuthorize(ChinookResources.AlbumActions.View, ChinookResources.Album)]
    public class AlbumController : Controller
    {
        IMusicRepository _musicRepository;

        public AlbumController()
        {
            _musicRepository = new Chinook.Repository.InMemory.MusicRepository();
        }

        public ActionResult Index(int page = 1)
        {
            var vm = new AlbumIndexViewModel(this._musicRepository, page);
            return View("Index", vm);
        }

        public ActionResult Edit(int id)
        {
            if (!HttpContext.CheckAccess(
                ChinookResources.AlbumActions.Edit,
                ChinookResources.Album,
                id.ToString()))
            {
                return this.AccessDenied();
            }

            var album = _musicRepository.GetAlbum(id);
            if (album == null) return RedirectToAction("Index");

            var vm = new AlbumEditViewModel(album, _musicRepository);
            return View("Edit", vm);
        }

        [HttpPost]
        public ActionResult Update(AlbumInputModel album)
        {
            if (!HttpContext.CheckAccess(
                ChinookResources.AlbumActions.Edit, 
                ChinookResources.Album, 
                album.AlbumID.ToString()))
            {
                return this.AccessDenied();
            }

            _musicRepository.SaveAlbum(album.GetAlbum());

            return RedirectToAction("Index");
        }

        public ActionResult AlbumCover(int id)
        {
            var image = _musicRepository.GetAlbumCoverImageByAlbumID(id);
            if (image != null) return File(image.Image, "image/jpeg");
            return File("~/Content/question-mark.png", "image/png");
        }

        public ActionResult ValidateAlbumTitle(
            [Bind(Prefix = "Album.AlbumID")] int albumID,
            [Bind(Prefix = "Album.Title")] string title)
        {
            var query =
                from a in _musicRepository.GetAlbums()
                where a.Title.ToLower() == title.ToLower() && a.AlbumID != albumID
                select a;
            var exists = query.Any();
            return Json(!exists, JsonRequestBehavior.AllowGet);
        }
    }
}

samples/OWIN/ResourceAuthorization/WebApp/Views/Shared/AlbumViewModelTable.cshtml
@model IEnumerable<WebApp.ViewModels.AlbumViewModel>

<table class="table table-condensed table-striped">
    <thead>
        <tr>
            <th></th>
            <th>Album Title</th>
            <th>Artist</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var album in Model)
        {
            <tr>
                <td>
                    @if(Context.CheckAccess(ChinookResources.AlbumActions.Edit, ChinookResources.Album))
                    {
                        @Html.ActionLink("edit", "Edit", "Album", new { id = album.AlbumID }, new { @class = "btn btn-primary" })
                    }
                    @*@if(User.IsInRole("Admin"))
                    { 
                        @Html.ActionLink("edit", "Edit", "Album", new { id = album.AlbumID }, new { @class = "btn btn-primary" })
                    }*@
                </td>
                <td>
                    @album.Title
                </td>
                <td>
                    @album.Artist
                </td>
                <td>
                    <img width="40" height="40"
                         src="@Url.Action("AlbumCover", "Album", new { id=album.AlbumID })" alt="@album.Title" />
                </td>
            </tr>
        }
    </tbody>
</table>

samples/OWIN/ResourceAuthorization/WebApp/Views/Shared/ChinookLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@(ViewData["Title"] ?? "Chinkook Music")</title>
    <link href="~/Content/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="~/">
                    Chinook Music
                </a>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse" id="menu">
                <ul class="nav navbar-nav">
                    <li><a href="~/Album">Albums</a></li>
                </ul>
                <div class="navbar-right">
                    @Html.Partial("CurrentUser")
                </div>
                <form action="~/Search" class="navbar-form navbar-right" method="get">
                    <div class="form-group">
                        <input type="text" name="phrase" placeholder="Search" class="form-control">
                    </div>
                    <button class="btn btn-default">Search</button>
                </form>
            </div>
        </div>
    </nav>

    <div class="container" id="main">
        @RenderBody()
    </div>

    <footer class="navbar-fixed-bottom navbar-inverse">
        <div class="navbar-text">Copyright @DateTime.Now.Year (not really, but it makes for a typical footer)</div>
    </footer>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Content/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    @RenderSection("scripts", false)

</body>
</html>

samples/OWIN/ResourceAuthorization/WebApp/Views/Shared/CurrentUser.cshtml
@if (Request.IsAuthenticated)
{
    <span class="navbar-text">Logged in as @User.Identity.Name</span>
    <a href="/Logout" class="btn btn-primary navbar-btn">Logout</a>
}
else
{
    <span class="navbar-text">Not Logged In</span>
    <a href="/Login" class="btn btn-primary navbar-btn">Login</a>
}

samples/OWIN/ResourceAuthorization/WebApp/Views/Shared/Forbidden.cshtml
@{
    Layout = "~/Views/Shared/ChinookLayout.cshtml";
}

<header class="page-header">
    <h1>Access Denied</h1>
    <p>You do not have access to that page.</p>
</header>